#!/usr/bin/env bash
set -e

staged=$(git diff --cached --name-only)
echo "Running cargo fmt..."
nix develop --command cargo fmt --all
if [ -n "$staged" ]; then
  echo "$staged" | xargs git add
fi

echo "Running cargo clippy..."
nix develop --command cargo clippy --all-targets --all-features -- -D warnings

echo "Pre-commit checks passed!"
